name: Generate Rules
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "Loyalsoldier_reject=https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt" >>$GITHUB_ENV
          echo "antiad_reject=https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml" >>$GITHUB_ENV
          echo "antiad_pcdn=https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/discretion/pcdn.txt" >>$GITHUB_ENV
          echo "antiad_dns=https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/discretion/dns.txt" >>$GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Collect reject 1
        run: |
          echo -n > reject-lines.txt
          curl -sSL ${Loyalsoldier_reject} -o Loyalsoldier_reject.yaml
          curl -sSL ${antiad_reject} -o antiad_reject.yaml
          curl -sSL ${antiad_pcdn} -o antiad_pcdn.txt
          curl -sSL ${antiad_dns} -o antiad_dns.txt
      - name: Collect reject 2
        uses: mikefarah/yq@master
        with:
          cmd: yq '. as $item ireduce ({}; . *+ $item) | .payload | .[]' Loyalsoldier_reject.yaml antiad_reject.yaml >> reject-lines.txt
      - name: Generate reject.txt
        run: |
          wc reject-lines.txt
          cat antiad_pcdn.txt | grep -v '#' | sed 's|^|+.|' > pcdn-lines.txt
          wc pcdn-lines.txt
          cat antiad_dns.txt | grep -v '#' | sed 's|^|+.|' > dns-lines.txt
          wc dns-lines.txt

          echo -n > reject.txt
          cat reject-lines.txt pcdn-lines.txt | sort | uniq >> reject.txt
          wc reject.txt
          echo -n > pcdn.txt
          cat pcdn-lines.txt | sort | uniq >> pcdn.txt
          wc pcdn.txt
          echo -n > dns.txt
          cat dns-lines.txt | sort | uniq >> dns.txt
          wc dns.txt

      - name: Git commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action[bot]"
          git add reject.txt
          git add pcdn.txt
          git add dns.txt
          git commit -m 'Auto update rules' || echo 'Nothing new'

      - name: Git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
