name: Generate Rules
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "Loyalsoldier_reject=https://github.com/Loyalsoldier/clash-rules/releases/download/202408022237/reject.txt" >>$GITHUB_ENV
          echo "antiad_reject=https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-clash.yaml" >>$GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Collect reject 1
        run: |
          echo -n > reject-lines.txt
          curl -sSL ${Loyalsoldier_reject} -o Loyalsoldier_reject.yaml
          curl -sSL ${antiad_reject} -o antiad_reject.yaml
      - name: Collect reject 2
        uses: mikefarah/yq@master
        with:
          cmd: yq '. as $item ireduce ({}; . *+ $item) | .payload | .[]' Loyalsoldier_reject.yaml antiad_reject.yaml >> reject-lines.txt
      - name: Generate reject.yaml
        run: |
          wc reject-lines.txt
          echo "payload:" > reject.yaml
          cat reject-lines.txt | sort | uniq | awk '{printf "- '%s'\n", $1}' >> reject.yaml
          wc reject.yaml

      - name: Git commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action[bot]"
          git add reject.yaml
          git commit -m 'Auto update rules' || echo 'Nothing new'

      - name: Git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
